apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: azuremachineproviderspecs.azureprovider.k8s.io
spec:
  group: azureprovider.k8s.io
  names:
    kind: AzureMachineProviderSpec
    plural: azuremachineproviderspecs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        image:
          properties:
            offer:
              type: string
            publisher:
              type: string
            sku:
              type: string
            version:
              type: string
          required:
          - publisher
          - offer
          - sku
          - version
          type: object
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        location:
          type: string
        metadata:
          type: object
        osDisk:
          properties:
            diskSizeGB:
              format: int32
              type: integer
            managedDisk:
              properties:
                storageAccountType:
                  type: string
              required:
              - storageAccountType
              type: object
            osType:
              type: string
          required:
          - osType
          - managedDisk
          - diskSizeGB
          type: object
        sshPrivateKey:
          type: string
        sshPublicKey:
          type: string
        vmSize:
          type: string
      required:
      - location
      - vmSize
      - image
      - osDisk
      - sshPublicKey
      - sshPrivateKey
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
