namespace: default
resources:
  - ../base
  - machine-deployment.yaml
  - ../../azure-cluster-identity

patches:
  - path: patches/kubeadm-controlplane.yaml
  - path: ../../azure-cluster-identity/azurecluster-identity-ref.yaml
