$patch: delete
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azureserviceoperator-controller-manager
  namespace: azureserviceoperator-system # This patch is processed before manifests-gen updates the namespace
