apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager # Name and namespace here are before any OpenShift modifications
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        args:
        - --leader-elect
        - --diagnostics-address=${CAPZ_DIAGNOSTICS_ADDRESS:=:8443}
        - --insecure-diagnostics=${CAPZ_INSECURE_DIAGNOSTICS:=false}
        - --feature-gates=MachinePool=${EXP_MACHINE_POOL:=false},AKSResourceHealth=${EXP_AKS_RESOURCE_HEALTH:=false},EdgeZone=${EXP_EDGEZONE:=false},ASOAPI=false
        - --v=0
