apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: capz-system
  name: capz-controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          args:
            - "--diagnostics-address=:8080"
            - "--insecure-diagnostics"
            - "--leader-elect"
            - "--feature-gates=MachinePool=${EXP_MACHINE_POOL:=true},AKSResourceHealth=${EXP_AKS_RESOURCE_HEALTH:=false},EdgeZone=${EXP_EDGEZONE:=false},ASOAPI=${EXP_ASO_API:=true},APIServerILB=${EXP_APISERVER_ILB:=false}"
            - "--enable-tracing"
